/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import java.sql.*;
import javax.swing.JPanel;


/**
 *
 * @author This pc
 */
public class fgt extends javax.swing.JPanel {

login frm;    
JPanel p1,p2; 
int k,mo,ep;
Connection con=null;
Statement st=null;
ResultSet rs=null;
conf cml;


public fgt(login abc,JPanel ab,JPanel ba) {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        p1=ab;
        p2=ba;
        frm=abc;
        k=0;
        mo=0;
        ep=0;
        p1.setLayout(new FlowLayout());
        t1.requestFocus();
        try
        {
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost/HGP","root","thakur");
        st=con.createStatement();
        }
        catch(Exception e){ }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        cb = new javax.swing.JComboBox();
        but2 = new javax.swing.JButton();
        but3 = new javax.swing.JButton();

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Email ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mobile");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Post");

        t1.setBackground(new java.awt.Color(255, 255, 204));
        t1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t1.setForeground(new java.awt.Color(51, 51, 51));
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setBorder(null);
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
        });

        t2.setBackground(new java.awt.Color(255, 255, 204));
        t2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t2.setForeground(new java.awt.Color(51, 51, 51));
        t2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t2.setBorder(null);
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t2KeyPressed(evt);
            }
        });

        t3.setBackground(new java.awt.Color(255, 255, 204));
        t3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t3.setForeground(new java.awt.Color(51, 51, 51));
        t3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t3.setBorder(null);
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t3KeyReleased(evt);
            }
        });

        cb.setBackground(new java.awt.Color(204, 204, 204));
        cb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb.setForeground(new java.awt.Color(51, 51, 51));
        cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Reception" }));
        cb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbMouseClicked(evt);
            }
        });
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });

        but2.setBackground(new java.awt.Color(0, 102, 102));
        but2.setFont(new java.awt.Font("Bell Gothic Std Light", 3, 24)); // NOI18N
        but2.setForeground(new java.awt.Color(255, 255, 255));
        but2.setText("Cancel");
        but2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        but2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        but2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2ActionPerformed(evt);
            }
        });

        but3.setBackground(new java.awt.Color(0, 102, 102));
        but3.setFont(new java.awt.Font("Bell Gothic Std Light", 3, 24)); // NOI18N
        but3.setForeground(new java.awt.Color(255, 255, 255));
        but3.setText("Submit");
        but3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        but3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        but3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(but2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(but3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2ActionPerformed
        lg f=new lg(frm,p1,p2);
        p1.setVisible(false);
        f.setVisible(true);
        p1.removeAll();
        p1.add(f);
        p1.setVisible(true);

         frm.er.setText("");
         p2.setVisible(false);   
         p2.setVisible(true);        
    }//GEN-LAST:event_but2ActionPerformed

    private void but3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but3ActionPerformed
        String name="";
        String pass="";
        
   String s1=t1.getText().trim();
   String s2=t2.getText().trim();
   String s3=t3.getText().trim();
   String s4=cb.getSelectedItem().toString().trim();
   
   if(mo==1 || s3.isEmpty())
   {
    t3.setBackground(Color.red);   
    t3.requestFocus();
   }

   if(!s2.endsWith(".com") || s2.isEmpty())
   {
    t2.setBackground(Color.red);   
    t2.requestFocus();
   }

   if(s1.isEmpty())
   {
    t1.setBackground(Color.red);   
    t1.requestFocus();
   }
           if(!s1.isEmpty() || !s2.isEmpty() || !s3.isEmpty())
        {
            String post="";
        try{
            rs=st.executeQuery("select nm,pass,post from emp where id='"+s1+"' AND mail='"+s2+"' AND mob='"+s3+"' AND post='"+s4+"';");
            while(rs.next())
        {  
         name=rs.getString(1);
         pass=rs.getString(2);
         post=rs.getString(3);
        }
        }catch(Exception e){System.out.print("error = "+e);}   
            
        if(post.equals("Reception"))
        {
            reception f=new reception(1,name);
            f.setLocationRelativeTo(null);
            f.setSize(1150,640);
            f.setVisible(true);
            frm.setVisible(false);
            cml=new conf(name,pass,1);
            cml.setLocationRelativeTo(null);
            cml.setVisible(true);
        }

       else if(post.equals("Admin"))
        {
            reception f=new reception(2,name);
            f.setLocationRelativeTo(null);
            f.setSize(1150,640);
            f.setVisible(true);
            frm.setVisible(false);
            cml=new conf(name,pass,1);
            cml.setLocationRelativeTo(null);
            cml.setVisible(true);
        }
        
       else{
         frm.er.setText(" ! Please Input Valid Deatails ...");
         p2.setVisible(false);   
         p2.setVisible(true);
       }
     }

    }//GEN-LAST:event_but3ActionPerformed

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
         if(k==1){
         p2.setVisible(false);   
         p2.setVisible(true);  }
         k=0;
        t1.requestFocus();
        t1.setBackground(new Color(255,255,204));
    }//GEN-LAST:event_t1KeyPressed

    private void t2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyPressed
         if(k==1){
         p2.setVisible(false);   
         p2.setVisible(true);  }
         k=0;
        t2.requestFocus();
        t2.setBackground(new Color(255,255,204));
    }//GEN-LAST:event_t2KeyPressed

    private void t3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyPressed
         if(k==1){
         p2.setVisible(false);   
         p2.setVisible(true);  }
         k=0;

         int key=evt.getKeyCode();
if((key>=evt.VK_0 && key<=evt.VK_9)||(key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACK_SPACE || key==evt.VK_LEFT || key==evt.VK_RIGHT)
{
 t3.setEditable(true);
 t3.setBackground(new Color(255,255,204));
}
else
{
 t3.setEditable(false);
}
   t3.requestFocus();
    }//GEN-LAST:event_t3KeyPressed

    private void t3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyReleased
        if(t3.getText().length()>10){
        t3.setEditable(true);
        t3.setBackground(Color.red);
        mo=1;
        }
        if(t3.getText().length()==10)mo=0;
        k=5;
    }//GEN-LAST:event_t3KeyReleased

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        if(k==1){
        p2.setVisible(false);
        p2.setVisible(true);
        }

       else if(k==5){
           if(t3.getText().length()>0 && t3.getText().length()<10)
           { 
             t3.setBackground(Color.red);
             mo=1;
       }}
        k=0;
    }//GEN-LAST:event_formMouseMoved

    private void cbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMouseClicked
k=1;
    }//GEN-LAST:event_cbMouseClicked

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        p2.setVisible(false);
        p2.setVisible(true);
    }//GEN-LAST:event_cbActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but2;
    private javax.swing.JButton but3;
    private javax.swing.JComboBox cb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
