package hotel;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JPanel;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class listrp extends javax.swing.JPanel {

JPanel rp;
Connection con=null;
Statement st=null;
ResultSet rs=null;
DefaultTableModel md=null;
String rec[][];
int i=0;

      public listrp(JPanel abc) {
        initComponents();
rp=abc;
this.setBackground(new Color(0,0,0,0));
tp.setBackground(new Color(0,0,0,0));
opt.setBackground(new Color(0,0,0,0));

tb.getTableHeader().setFont(new Font("tahoma",Font.PLAIN,16));
md=(DefaultTableModel)tb.getModel();

        try
        {
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost/HGP","root","thakur");
        st=con.createStatement();
        rs=st.executeQuery("select * from rooms;");
        while(rs.next())
        {
         i++;
        }       
        rs=st.executeQuery("select * from rooms;");
        rec=new String[i][5];
        i=0;
        while(rs.next())
        {
         rec[i][0]=""+(i+1);   
         rec[i][1]=rs.getString(1);
         rec[i][2]=rs.getString(2);
         rec[i][3]=rs.getString(3);
         rec[i][4]=rs.getString(4);
         i++;
        }       
    for(int j=0;j<i;j++)
    {
     md.addRow(rec[j]);
    } 
        }catch(Exception e){}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tp = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        opt = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        tb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb.setForeground(new java.awt.Color(102, 102, 102));
        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr No.", "Room No.", "Room Type", "Charges", "Status"
            }
        ));
        tb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tb.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tb.setEnabled(false);
        tb.setGridColor(new java.awt.Color(0, 0, 0));
        tb.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tb.setRowHeight(24);
        jScrollPane1.setViewportView(tb);

        javax.swing.GroupLayout tpLayout = new javax.swing.GroupLayout(tp);
        tp.setLayout(tpLayout);
        tpLayout.setHorizontalGroup(
            tpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        tpLayout.setVerticalGroup(
            tpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Default");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Price");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Print");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optLayout = new javax.swing.GroupLayout(opt);
        opt.setLayout(optLayout);
        optLayout.setHorizontalGroup(
            optLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        optLayout.setVerticalGroup(
            optLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(opt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    for(int j=0;j<i;j++) md.removeRow(0);
     String ind[][]=new String[i][5];
for(int j=0;j<i;j++)
{
ind[j][0]=rec[j][0];
ind[j][1]=rec[j][1];
ind[j][2]=rec[j][2];
ind[j][3]=rec[j][3];
ind[j][4]=rec[j][4];
}
     
     
for(int j=0;j<i-1;j++)
{
 for(int k=j+1;k<i;k++)
{
  if(Integer.parseInt(ind[j][3])>=Integer.parseInt(ind[k][3]))  
  {
    String strr=ind[j][1];
    ind[j][1]=ind[k][1];
    ind[k][1]=strr;
    
    strr=ind[j][2];
    ind[j][2]=ind[k][2];
    ind[k][2]=strr;

    strr=ind[j][3];
    ind[j][3]=ind[k][3];
    ind[k][3]=strr;

    strr=ind[j][4];
    ind[j][4]=ind[k][4];
    ind[k][4]=strr;  }
 }
}
    for(int j=0;j<i;j++) md.addRow(ind[j]);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try
{
 MessageFormat header=new MessageFormat("Rooms Details.");
 MessageFormat fter=new MessageFormat("");
 tb.print(JTable.PrintMode.FIT_WIDTH,header,fter);
}catch(Exception e){}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    for(int j=0;j<i;j++) md.removeRow(0);
    for(int j=0;j<i;j++) md.addRow(rec[j]);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel opt;
    private javax.swing.JTable tb;
    private javax.swing.JPanel tp;
    // End of variables declaration//GEN-END:variables
}
