package hotel;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JPanel;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class listcp extends javax.swing.JPanel {

JPanel rp;
Connection con=null;
Statement st=null;
ResultSet rs=null;
DefaultTableModel md=null;
String rec[][],in[][],out[][];
int i=0,l=0,ck=0;

     public listcp(JPanel abc) {
        initComponents();
rp=abc;
this.setBackground(new Color(0,0,0,0));
tp.setBackground(new Color(0,0,0,0));
opt.setBackground(new Color(0,0,0,0));

tb.getTableHeader().setFont(new Font("tahoma",Font.PLAIN,16));
md=(DefaultTableModel)tb.getModel();

        try
        {
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost/HGP","root","thakur");
        st=con.createStatement();
        rs=st.executeQuery("select id from booked;");
        while(rs.next())
        {
         i++;
         rs.getString(1);
        }   
        in=new String[i][7];
        i=0;
        rs=st.executeQuery("select id,nm,rno,city,mob,cin,cout from booked;");
        while(rs.next())
        {
         in[i][0]=rs.getString(1);
         in[i][1]=rs.getString(2);
         in[i][2]=rs.getString(3);
         in[i][3]=rs.getString(4);
         in[i][4]=rs.getString(5);
         in[i][5]=rs.getString(6);
         in[i][6]=rs.getString(7);
         i++;
        }       
        l=i;
        rs=st.executeQuery("select id from hdb;");
        while(rs.next())
        {
         i++;
         rs.getString(1);
        }   
        out=new String[i-l][7];
        l=0;
        rs=st.executeQuery("select id,nm,rno,city,mob,cin,cout from hdb;");
        while(rs.next())
        {
         out[l][0]=rs.getString(1);
         out[l][1]=rs.getString(2);
         out[l][2]=rs.getString(3);
         out[l][3]=rs.getString(4);
         out[l][4]=rs.getString(5);
         out[l][5]=rs.getString(6);
         out[l][6]=rs.getString(7);
         l++;
        } 
        
        rec=new String[i][6];
        int p=0;
    for(int j=0;j<i;j++)
    {
     if(j<(i-l)) for(int k=0;k<6;k++)rec[j][k]=in[j][k];
            else { for(int k=0;k<6;k++)rec[j][k]=out[p][k];  p++; }
     md.addRow(rec[j]);
    } 
        }catch(Exception e){System.out.print("Error = "+e);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tp = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        opt = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        tb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb.setForeground(new java.awt.Color(102, 102, 102));
        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Room No.", "City", "Mobile no.", "Check in"
            }
        ));
        tb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tb.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tb.setEnabled(false);
        tb.setGridColor(new java.awt.Color(0, 0, 0));
        tb.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tb.setRowHeight(24);
        jScrollPane1.setViewportView(tb);

        javax.swing.GroupLayout tpLayout = new javax.swing.GroupLayout(tp);
        tp.setLayout(tpLayout);
        tpLayout.setHorizontalGroup(
            tpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        tpLayout.setVerticalGroup(
            tpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        opt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Defalut");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Name");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Room No.");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("City");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 51));
        jButton5.setText("Cin");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 51, 51));
        jButton7.setText("Cout");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 51));
        jButton6.setText("Print");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optLayout = new javax.swing.GroupLayout(opt);
        opt.setLayout(optLayout);
        optLayout.setHorizontalGroup(
            optLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );
        optLayout.setVerticalGroup(
            optLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(opt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
try
{
 MessageFormat header=new MessageFormat("Customer Details.");
 MessageFormat fter=new MessageFormat("");
 tb.print(JTable.PrintMode.FIT_WIDTH,header,fter);
}catch(Exception e){}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String ind[][];
int p=0;
if(ck==1) 
{
for(int j=0;j<i-l;j++) md.removeRow(0);

ind=new String[i-l][6];
for(int j=0;j<i-l;j++)
{
ind[j][0]=in[j][0];
ind[j][1]=in[j][1];
ind[j][2]=in[j][2];
ind[j][3]=in[j][3];
ind[j][4]=in[j][4];
ind[j][5]=in[j][5];
} 
p=i-l;
}
else if(ck==2) 
{
for(int j=0;j<l;j++) md.removeRow(0);

ind=new String[l][6];
for(int j=0;j<l;j++)
{
ind[j][0]=out[j][0];
ind[j][1]=out[j][1];
ind[j][2]=out[j][2];
ind[j][3]=out[j][3];
ind[j][4]=out[j][4];
ind[j][5]=out[j][5];
} 
p=l;
}
else
{
for(int j=0;j<i;j++) md.removeRow(0);

ind=new String[i][6];
for(int j=0;j<i;j++)
{
ind[j][0]=rec[j][0];
ind[j][1]=rec[j][1];
ind[j][2]=rec[j][2];
ind[j][3]=rec[j][3];
ind[j][4]=rec[j][4];
ind[j][5]=rec[j][5];
} 
p=i;
}

for(int j=0;j<p-1;j++)
{
 for(int k=j+1;k<p;k++)
{
  if(ind[j][1].compareToIgnoreCase(ind[k][1])>0)  
  {
    String strr=ind[j][0];
    ind[j][0]=ind[k][0];
    ind[k][0]=strr;
    
    strr=ind[j][1];
    ind[j][1]=ind[k][1];
    ind[k][1]=strr;  

    strr=ind[j][2];
    ind[j][2]=ind[k][2];
    ind[k][2]=strr;

    strr=ind[j][3];
    ind[j][3]=ind[k][3];
    ind[k][3]=strr;

    strr=ind[j][4];
    ind[j][4]=ind[k][4];
    ind[k][4]=strr;  
  
    strr=ind[j][5];
    ind[j][5]=ind[k][5];
    ind[k][5]=strr;  
  
  }
 }
}
for(int j=0;j<p;j++) md.addRow(ind[j]);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String ind[][];
int p=0;
if(ck==1) 
{
for(int j=0;j<i-l;j++) md.removeRow(0);

ind=new String[i-l][6];
for(int j=0;j<i-l;j++)
{
ind[j][0]=in[j][0];
ind[j][1]=in[j][1];
ind[j][2]=in[j][2];
ind[j][3]=in[j][3];
ind[j][4]=in[j][4];
ind[j][5]=in[j][5];
} 
p=i-l;
}
else if(ck==2) 
{
for(int j=0;j<l;j++) md.removeRow(0);

ind=new String[l][6];
for(int j=0;j<l;j++)
{
ind[j][0]=out[j][0];
ind[j][1]=out[j][1];
ind[j][2]=out[j][2];
ind[j][3]=out[j][3];
ind[j][4]=out[j][4];
ind[j][5]=out[j][5];
} 
p=l;
}
else
{
for(int j=0;j<i;j++) md.removeRow(0);

ind=new String[i][6];
for(int j=0;j<i;j++)
{
ind[j][0]=rec[j][0];
ind[j][1]=rec[j][1];
ind[j][2]=rec[j][2];
ind[j][3]=rec[j][3];
ind[j][4]=rec[j][4];
ind[j][5]=rec[j][5];
} 
p=i;
}

for(int j=0;j<p-1;j++)
{
 for(int k=j+1;k<p;k++)
{
  if(ind[j][3].compareToIgnoreCase(ind[k][3])>0)  
  {
    String strr=ind[j][0];
    ind[j][0]=ind[k][0];
    ind[k][0]=strr;
    
    strr=ind[j][1];
    ind[j][1]=ind[k][1];
    ind[k][1]=strr;  

    strr=ind[j][2];
    ind[j][2]=ind[k][2];
    ind[k][2]=strr;

    strr=ind[j][3];
    ind[j][3]=ind[k][3];
    ind[k][3]=strr;

    strr=ind[j][4];
    ind[j][4]=ind[k][4];
    ind[k][4]=strr;  
  
    strr=ind[j][5];
    ind[j][5]=ind[k][5];
    ind[k][5]=strr;  
  
  }
 }
}
for(int j=0;j<p;j++) md.addRow(ind[j]);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String ind[][];
int p=0;
if(ck==1) 
{
for(int j=0;j<i-l;j++) md.removeRow(0);

ind=new String[i-l][6];
for(int j=0;j<i-l;j++)
{
ind[j][0]=in[j][0];
ind[j][1]=in[j][1];
ind[j][2]=in[j][2];
ind[j][3]=in[j][3];
ind[j][4]=in[j][4];
ind[j][5]=in[j][5];
} 
p=i-l;
}
else if(ck==2) 
{
for(int j=0;j<l;j++) md.removeRow(0);

ind=new String[l][6];
for(int j=0;j<l;j++)
{
ind[j][0]=out[j][0];
ind[j][1]=out[j][1];
ind[j][2]=out[j][2];
ind[j][3]=out[j][3];
ind[j][4]=out[j][4];
ind[j][5]=out[j][5];
} 
p=l;
}
else
{
for(int j=0;j<i;j++) md.removeRow(0);

ind=new String[i][6];
for(int j=0;j<i;j++)
{
ind[j][0]=rec[j][0];
ind[j][1]=rec[j][1];
ind[j][2]=rec[j][2];
ind[j][3]=rec[j][3];
ind[j][4]=rec[j][4];
ind[j][5]=rec[j][5];
} 
p=i;
}

for(int j=0;j<p-1;j++)
{
 for(int k=j+1;k<p;k++)
{
  if(Integer.parseInt(ind[j][2])>=Integer.parseInt(ind[k][2]))  
  {
    String strr=ind[j][0];
    ind[j][0]=ind[k][0];
    ind[k][0]=strr;
    
    strr=ind[j][1];
    ind[j][1]=ind[k][1];
    ind[k][1]=strr;  

    strr=ind[j][2];
    ind[j][2]=ind[k][2];
    ind[k][2]=strr;

    strr=ind[j][3];
    ind[j][3]=ind[k][3];
    ind[k][3]=strr;

    strr=ind[j][4];
    ind[j][4]=ind[k][4];
    ind[k][4]=strr;  
  
    strr=ind[j][5];
    ind[j][5]=ind[k][5];
    ind[k][5]=strr;  
  
  }
 }
}
for(int j=0;j<p;j++) md.addRow(ind[j]);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

if(ck==1) 
{
for(int j=0;j<i-l;j++) md.removeRow(0);
}

else if(ck==2) 
{
for(int j=0;j<l;j++) md.removeRow(0);
}

else
{
for(int j=0;j<i;j++) md.removeRow(0);
}

for(int j=0;j<i-l;j++) md.addRow(in[j]);

ck=1;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
if(ck==1) 
{
for(int j=0;j<i-l;j++) md.removeRow(0);
}

else if(ck==2) 
{
for(int j=0;j<l;j++) md.removeRow(0);
}

else
{
for(int j=0;j<i;j++) md.removeRow(0);
}

for(int j=0;j<l;j++) md.addRow(out[j]);

ck=2;
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(ck==1) 
{
for(int j=0;j<i-l;j++) md.removeRow(0);
}

else if(ck==2) 
{
for(int j=0;j<l;j++) md.removeRow(0);
}

else
{
for(int j=0;j<i;j++) md.removeRow(0);
}

for(int j=0;j<i;j++) md.addRow(rec[j]);

ck=0;

    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel opt;
    private javax.swing.JTable tb;
    private javax.swing.JPanel tp;
    // End of variables declaration//GEN-END:variables
}
