package hotel;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JPanel;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class listep extends javax.swing.JPanel {

JPanel rp;
Connection con=null;
Statement st=null;
ResultSet rs=null;
DefaultTableModel md=null;
String rec[][];
int i=0;

     public listep(JPanel abc) {
        initComponents();
rp=abc;
this.setBackground(new Color(0,0,0,0));
tp.setBackground(new Color(0,0,0,0));
opt.setBackground(new Color(0,0,0,0));

tb.getTableHeader().setFont(new Font("tahoma",Font.PLAIN,16));
md=(DefaultTableModel)tb.getModel();

        try
        {
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost/HGP","root","thakur");
        st=con.createStatement();
        rs=st.executeQuery("select * from emp;");
        while(rs.next())
        {
         i++;
        }       
        rs=st.executeQuery("select id,nm,city,mob,post,salary,jin,resign from emp;");
        rec=new String[i][8];
        i=0;
        while(rs.next())
        {
         rec[i][0]=rs.getString(1);   
         rec[i][1]=rs.getString(2);
         rec[i][2]=rs.getString(3);
         rec[i][3]=rs.getString(4);
         rec[i][4]=rs.getString(5);
         rec[i][5]=rs.getString(6);
         rec[i][6]=rs.getString(7);
         rec[i][7]=rs.getString(8);      
         i++;
        }       
    for(int j=0;j<i;j++)
    {
     md.addRow(rec[j]);
    } 
        }catch(Exception e){}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        tp = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        opt = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 51));
        jButton6.setText("Defalut");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb.setForeground(new java.awt.Color(102, 102, 102));
        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Emp Name", "City", "Mobile No.", "Post", "Salary", "Joining"
            }
        ));
        tb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tb.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        tb.setEnabled(false);
        tb.setGridColor(new java.awt.Color(0, 0, 0));
        tb.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tb.setRowHeight(24);
        jScrollPane1.setViewportView(tb);

        javax.swing.GroupLayout tpLayout = new javax.swing.GroupLayout(tp);
        tp.setLayout(tpLayout);
        tpLayout.setHorizontalGroup(
            tpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        tpLayout.setVerticalGroup(
            tpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Defalut");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Name");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Salary");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("City");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 51));
        jButton5.setText("working");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 51, 51));
        jButton7.setText("Not Working");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(51, 51, 51));
        jButton8.setText("Print");
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optLayout = new javax.swing.GroupLayout(opt);
        opt.setLayout(optLayout);
        optLayout.setHorizontalGroup(
            optLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optLayout.createSequentialGroup()
                .addGroup(optLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(optLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        optLayout.setVerticalGroup(
            optLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(opt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(opt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
try
{
 MessageFormat header=new MessageFormat("Employee Deatils.");
 MessageFormat fter=new MessageFormat("");
 tb.print(JTable.PrintMode.FIT_WIDTH,header,fter);
}catch(Exception e){}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
for(int j=0;j<i;j++) md.removeRow(0);

String ind[][]=new String[i][7];
for(int j=0;j<i;j++)
{
ind[j][0]=rec[j][0];
ind[j][1]=rec[j][1];
ind[j][2]=rec[j][2];
ind[j][3]=rec[j][3];
ind[j][4]=rec[j][4];
ind[j][5]=rec[j][5];
ind[j][6]=rec[j][6];
}
     
     
for(int j=0;j<i-1;j++)
{
 for(int k=j+1;k<i;k++)
{
  if(ind[j][1].compareToIgnoreCase(ind[k][1])>0)  
  {
    String strr=ind[j][0];
    ind[j][0]=ind[k][0];
    ind[k][0]=strr;
    
    strr=ind[j][1];
    ind[j][1]=ind[k][1];
    ind[k][1]=strr;  

    strr=ind[j][2];
    ind[j][2]=ind[k][2];
    ind[k][2]=strr;

    strr=ind[j][3];
    ind[j][3]=ind[k][3];
    ind[k][3]=strr;

    strr=ind[j][4];
    ind[j][4]=ind[k][4];
    ind[k][4]=strr;  
  
    strr=ind[j][5];
    ind[j][5]=ind[k][5];
    ind[k][5]=strr;  
  
    strr=ind[j][6];
    ind[j][6]=ind[k][6];
    ind[k][6]=strr;  
  
  }
 }
}
for(int j=0;j<i;j++) md.addRow(ind[j]);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
for(int j=0;j<i;j++) md.removeRow(0);

try{
    rs=st.executeQuery("select * from emp;");
        while(rs.next())
        {
         i++;
        }       
        rs=st.executeQuery("select id,nm,city,mob,post,salary,jin,resign from emp;");
        rec=new String[i][8];
        i=0;
        while(rs.next())
        {
         rec[i][0]=rs.getString(1);   
         rec[i][1]=rs.getString(2);
         rec[i][2]=rs.getString(3);
         rec[i][3]=rs.getString(4);
         rec[i][4]=rs.getString(5);
         rec[i][5]=rs.getString(6);
         rec[i][6]=rs.getString(7);
         rec[i][7]=rs.getString(8);      
         i++;
        }       
    for(int j=0;j<i;j++)
    {
     md.addRow(rec[j]);
    } 
        }catch(Exception e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
for(int j=0;j<i;j++) md.removeRow(0);

String ind[][]=new String[i][7];
for(int j=0;j<i;j++)
{
ind[j][0]=rec[j][0];
ind[j][1]=rec[j][1];
ind[j][2]=rec[j][2];
ind[j][3]=rec[j][3];
ind[j][4]=rec[j][4];
ind[j][5]=rec[j][5];
ind[j][6]=rec[j][6];
}
     
     
for(int j=0;j<i-1;j++)
{
 for(int k=j+1;k<i;k++)
{
  if(Integer.parseInt(ind[j][5])>=Integer.parseInt(ind[k][5]))  
  {
    String strr=ind[j][0];
    ind[j][0]=ind[k][0];
    ind[k][0]=strr;
    
    strr=ind[j][1];
    ind[j][1]=ind[k][1];
    ind[k][1]=strr;  

    strr=ind[j][2];
    ind[j][2]=ind[k][2];
    ind[k][2]=strr;

    strr=ind[j][3];
    ind[j][3]=ind[k][3];
    ind[k][3]=strr;

    strr=ind[j][4];
    ind[j][4]=ind[k][4];
    ind[k][4]=strr;  
  
    strr=ind[j][5];
    ind[j][5]=ind[k][5];
    ind[k][5]=strr;  
  
    strr=ind[j][6];
    ind[j][6]=ind[k][6];
    ind[k][6]=strr;  
  
  }
 }
}
for(int j=0;j<i;j++) md.addRow(ind[j]);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
for(int j=0;j<i;j++) md.removeRow(0);

String ind[][]=new String[i][7];
for(int j=0;j<i;j++)
{
ind[j][0]=rec[j][0];
ind[j][1]=rec[j][1];
ind[j][2]=rec[j][2];
ind[j][3]=rec[j][3];
ind[j][4]=rec[j][4];
ind[j][5]=rec[j][5];
ind[j][6]=rec[j][6];
}
     
     
for(int j=0;j<i-1;j++)
{
 for(int k=j+1;k<i;k++)
{
  if(ind[j][2].compareToIgnoreCase(ind[k][2])>0)  
  {
    String strr=ind[j][0];
    ind[j][0]=ind[k][0];
    ind[k][0]=strr;
    
    strr=ind[j][1];
    ind[j][1]=ind[k][1];
    ind[k][1]=strr;  

    strr=ind[j][2];
    ind[j][2]=ind[k][2];
    ind[k][2]=strr;

    strr=ind[j][3];
    ind[j][3]=ind[k][3];
    ind[k][3]=strr;

    strr=ind[j][4];
    ind[j][4]=ind[k][4];
    ind[k][4]=strr;  
  
    strr=ind[j][5];
    ind[j][5]=ind[k][5];
    ind[k][5]=strr;  
  
    strr=ind[j][6];
    ind[j][6]=ind[k][6];
    ind[k][6]=strr;  
  
  }
 }
}
for(int j=0;j<i;j++) md.addRow(ind[j]);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
for(int j=0;j<i;j++) md.removeRow(0);
try{
    rs=st.executeQuery("select * from emp;");
        while(rs.next())
        {
         i++;
        }       
        rs=st.executeQuery("select id,nm,city,mob,post,salary,jin,resign from emp;");
        rec=new String[i][8];
        i=0;
        while(rs.next())
        {
         rec[i][0]=rs.getString(1);   
         rec[i][1]=rs.getString(2);
         rec[i][2]=rs.getString(3);
         rec[i][3]=rs.getString(4);
         rec[i][4]=rs.getString(5);
         rec[i][5]=rs.getString(6);
         rec[i][6]=rs.getString(7);
         rec[i][7]=rs.getString(8);      
         i++;
        }       
        }catch(Exception e){}

int l=0;
    for(int j=0;j<i;j++)
    {
        if(rec[j][7].equals("Dont Know"))
        {
        l++;
        }
    }
    
String ind[][]=new String[l][8];
l=0;
for(int j=0;j<i;j++)
{
  if(rec[j][7].equals("Dont Know"))
   {
      for(int k=0;k<8;k++)
        {       
        ind[l][k]=rec[j][k];    
        }
      l++;
   }   
}
i=l;
rec=new String[i][8];
for(int j=0;j<i;j++)
{
      for(int k=0;k<8;k++)
        {       
        rec[j][k]=ind[j][k];    
        }
    md.addRow(rec[j]);
} 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
for(int j=0;j<i;j++) md.removeRow(0);
try{
    rs=st.executeQuery("select * from emp;");
        while(rs.next())
        {
         i++;
        }       
        rs=st.executeQuery("select id,nm,city,mob,post,salary,jin,resign from emp;");
        rec=new String[i][8];
        i=0;
        while(rs.next())
        {
         rec[i][0]=rs.getString(1);   
         rec[i][1]=rs.getString(2);
         rec[i][2]=rs.getString(3);
         rec[i][3]=rs.getString(4);
         rec[i][4]=rs.getString(5);
         rec[i][5]=rs.getString(6);
         rec[i][6]=rs.getString(7);
         rec[i][7]=rs.getString(8);      
         i++;
        }       
        }catch(Exception e){}
int l=0;
    for(int j=0;j<i;j++)
    {
        if(!rec[j][7].equals("Dont Know"))
        {
        l++;
        }
    }
    
String ind[][]=new String[l][8];
l=0;
for(int j=0;j<i;j++)
{
  if(!rec[j][7].equals("Dont Know"))
   {
      for(int k=0;k<8;k++)
        {       
        ind[l][k]=rec[j][k];    
        }
      l++;
   }   
}
i=l;
rec=new String[i][8];
for(int j=0;j<i;j++)
{
      for(int k=0;k<8;k++)
        {       
        rec[j][k]=ind[j][k];    
        }
    md.addRow(rec[j]);
}     }//GEN-LAST:event_jButton7ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel opt;
    private javax.swing.JTable tb;
    private javax.swing.JPanel tp;
    // End of variables declaration//GEN-END:variables
}
