
package hotel;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class modep extends javax.swing.JPanel {

    JPanel rp;
    int k=0,mo,em;

Connection con=null;
Statement st=null;
ResultSet rs=null;

public modep(JPanel abc) {
        rp=abc;
        mo=0;
        em=0;
        initComponents();
this.setBackground(new Color(0,0,0,0));
ep.setBackground(new Color(0,0,0,0));
ri.setBackground(new Color(0,0,0,0));

ep.setVisible(false);

        try
        {
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost/HGP","root","thakur");
        st=con.createStatement();
        }
        catch(Exception e)
        { System.out.print(e); }
        
        t1.setEditable(false);
        t3.setEditable(false);
        t4.setEditable(false);
        t5.setEditable(false);
        t6.setEditable(false);
        t7.setEditable(false);
        t8.setEditable(false);
        t9.setEditable(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ep = new javax.swing.JPanel();
        error = new javax.swing.JLabel();
        ri = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        but = new javax.swing.JButton();
        cb2 = new javax.swing.JComboBox();
        t1 = new javax.swing.JTextField();
        go = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        l10 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();

        error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        error.setForeground(new java.awt.Color(204, 255, 204));
        error.setText("! Error");

        javax.swing.GroupLayout epLayout = new javax.swing.GroupLayout(ep);
        ep.setLayout(epLayout);
        epLayout.setHorizontalGroup(
            epLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );
        epLayout.setVerticalGroup(
            epLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        ri.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                riMouseMoved(evt);
            }
        });

        l1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("Name");

        l3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText("Address");

        l5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 255, 255));
        l5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l5.setText("City");

        l7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l7.setForeground(new java.awt.Color(255, 255, 255));
        l7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l7.setText("Mobile No.");

        l9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l9.setForeground(new java.awt.Color(255, 255, 255));
        l9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l9.setText("Salary");

        l6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l6.setForeground(new java.awt.Color(255, 255, 255));
        l6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l6.setText("Email");

        l8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l8.setForeground(new java.awt.Color(255, 255, 255));
        l8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l8.setText("Joining Date");

        t4.setBackground(new java.awt.Color(255, 255, 204));
        t4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t4.setForeground(new java.awt.Color(51, 51, 51));
        t4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t4KeyPressed(evt);
            }
        });

        t7.setBackground(new java.awt.Color(255, 255, 204));
        t7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t7.setForeground(new java.awt.Color(51, 51, 51));
        t7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t7KeyPressed(evt);
            }
        });

        t8.setBackground(new java.awt.Color(255, 255, 204));
        t8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t8.setForeground(new java.awt.Color(51, 51, 51));
        t8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t8KeyPressed(evt);
            }
        });

        t6.setBackground(new java.awt.Color(255, 255, 204));
        t6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t6.setForeground(new java.awt.Color(51, 51, 51));
        t6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        t6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t6KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t6KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t6KeyTyped(evt);
            }
        });

        t9.setBackground(new java.awt.Color(255, 255, 204));
        t9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t9.setForeground(new java.awt.Color(51, 51, 51));
        t9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t9KeyPressed(evt);
            }
        });

        t5.setBackground(new java.awt.Color(255, 255, 204));
        t5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t5.setForeground(new java.awt.Color(51, 51, 51));
        t5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t5KeyPressed(evt);
            }
        });

        t10.setEditable(false);
        t10.setBackground(new java.awt.Color(255, 255, 204));
        t10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t10.setForeground(new java.awt.Color(51, 51, 51));
        t10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        but.setBackground(new java.awt.Color(0, 102, 102));
        but.setFont(new java.awt.Font("Bell Gothic Std Light", 3, 24)); // NOI18N
        but.setForeground(new java.awt.Color(255, 255, 255));
        but.setText("SAVE");
        but.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        but.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butActionPerformed(evt);
            }
        });

        cb2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb2.setForeground(new java.awt.Color(51, 51, 51));
        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Search", "Employee ID", "Mobile No", "Email ID" }));
        cb2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cb2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb2MouseClicked(evt);
            }
        });
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        t1.setBackground(new java.awt.Color(255, 255, 204));
        t1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t1.setForeground(new java.awt.Color(51, 51, 51));
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t1KeyReleased(evt);
            }
        });

        go.setBackground(new java.awt.Color(0, 102, 102));
        go.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        go.setForeground(new java.awt.Color(255, 255, 255));
        go.setText("Go");
        go.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        go.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });

        l2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText("Eployee ID");

        t2.setEditable(false);
        t2.setBackground(new java.awt.Color(255, 255, 204));
        t2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t2.setForeground(new java.awt.Color(51, 51, 51));
        t2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        l10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l10.setForeground(new java.awt.Color(255, 255, 255));
        l10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l10.setText("Password");

        t3.setBackground(new java.awt.Color(255, 255, 204));
        t3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t3.setForeground(new java.awt.Color(51, 51, 51));
        t3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t3KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout riLayout = new javax.swing.GroupLayout(ri);
        ri.setLayout(riLayout);
        riLayout.setHorizontalGroup(
            riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, riLayout.createSequentialGroup()
                        .addComponent(but, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(riLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(riLayout.createSequentialGroup()
                                .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(riLayout.createSequentialGroup()
                                .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(riLayout.createSequentialGroup()
                                .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(l9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(l3, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(riLayout.createSequentialGroup()
                .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(riLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(go, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(riLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        riLayout.setVerticalGroup(
            riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(go))
                .addGap(55, 55, 55)
                .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(riLayout.createSequentialGroup()
                        .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(but, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(riLayout.createSequentialGroup()
                        .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(ep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(ri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void riMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riMouseMoved
        if(k==1){
        rp.setVisible(false);
        rp.setVisible(true);
        }

       else if(k==5){
           if(t1.getText().length()>0 && t1.getText().length()<10)
           { 
               t1.setEditable(true);
               t1.setBackground(Color.red);
       }}

       else if(k==15){
           if(t6.getText().length()>0 && t6.getText().length()<10)
           { 
               t6.setEditable(true);
               t6.setBackground(Color.red);
       }}
        k=0;
    }//GEN-LAST:event_riMouseMoved

    private void t6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t6KeyTyped

    }//GEN-LAST:event_t6KeyTyped

    private void t6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t6KeyPressed
        ep.setVisible(false);
        rp.setVisible(false);
        rp.setVisible(true);

int key=evt.getKeyCode();
if((key>=evt.VK_0 && key<=evt.VK_9)||(key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACK_SPACE || key==evt.VK_LEFT || key==evt.VK_RIGHT)
{
 t6.setEditable(true);
 t6.setBackground(new Color(255,255,204));
}
else
{
 t6.setEditable(false);
}
   t6.requestFocus();

    }//GEN-LAST:event_t6KeyPressed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed

    }//GEN-LAST:event_t6ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        t1.setText("");   
        t1.setEditable(true);
        t1.setBackground(new Color(255,255,204));

         t2.setText("");   
         t3.setText("");   
         t4.setText("");   
         t5.setText("");   
         t6.setText("");   
         t6.setEditable(true);
         t6.setBackground(new Color(255,255,204));
         t7.setText("");   
         t8.setText("");   
         t9.setText("");   
         t10.setText("");   
        t1.setEditable(true);
        t3.setEditable(false);
        t4.setEditable(false);
        t5.setEditable(false);
        t6.setEditable(false);
        t7.setEditable(false);
        t8.setEditable(false);
        t9.setEditable(false);

        if(cb2.getSelectedIndex()==0)
        {
        t1.setEditable(false);
       }
        if(cb2.getSelectedIndex()==1)
        {
        t1.setEditable(false);
        t1.setText("HGPE");
        t1.setEditable(true);
       }
         ep.setVisible(false); 
         rp.setVisible(false);
         rp.setVisible(true);
         t1.requestFocus();
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb2MouseClicked
        k=1;
        // TODO add your handling code here:
    }//GEN-LAST:event_cb2MouseClicked

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
    ep.setVisible(false);        // TODO add your handling code here:
        rp.setVisible(false);
        rp.setVisible(true);

if(cb2.getSelectedIndex()==2){
int key=evt.getKeyCode();
if((key>=evt.VK_0 && key<=evt.VK_9)||(key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACK_SPACE || key==evt.VK_LEFT || key==evt.VK_RIGHT)
{
 t1.setEditable(true);
 t1.setBackground(new Color(255,255,204));
}
else{
 t1.setEditable(false);
}
   }
        t1.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_t1KeyPressed

    private void t1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyReleased
        if(cb2.getSelectedIndex()==2){
        if(t1.getText().length()>10){
        t1.setEditable(true);
        t1.setBackground(Color.red);
        }
        k=5;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_t1KeyReleased

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        String gd=t1.getText();
        if(gd.isEmpty())
        {
        ep.setVisible(true);    
        error.setText(" Please Input Customer ID ... ");
        rp.setVisible(false);
        rp.setVisible(true); 
        }

        else{
        String rec[]=new String[10];
        int bj=0,ck=0;
        try{

           if(cb2.getSelectedIndex()==1)
           {
           rs=st.executeQuery("select * from emp where id='"+gd+"';");
           bj=101;
           }

           if(cb2.getSelectedIndex()==2)
           {
           rs=st.executeQuery("select * from emp where mob='"+gd+"';");
           bj=102;
           }

           if(cb2.getSelectedIndex()==3)
           {
           rs=st.executeQuery("select * from emp where mail='"+gd+"';");
           bj=103;
           }

            while(rs.next())
        {  
            ck=1; 
            rec[0]=rs.getString(1);
            rec[1]=rs.getString(2);
            rec[2]=rs.getString(3);
            rec[3]=rs.getString(4);
            rec[4]=rs.getString(5);
            rec[5]=rs.getString(6);
            rec[6]=rs.getString(7);
            rs.getString(8);
            rec[7]=rs.getString(9);
            rec[8]=rs.getString(10);
            rec[9]=rs.getString(11);
            
        }
       
        if(ck==1)
        {
        t2.setText(rec[0]);
        t3.setText(rec[1]);
        t4.setText(rec[2]);
        t5.setText(rec[5]);
        t6.setText(rec[6]);
        t7.setText(rec[3]);
        t8.setText(rec[4]);
        t9.setText(rec[7]);
        t10.setText(rec[8]);

        if(rec[1].equals("None"))t3.setEditable(false);
        else t3.setEditable(true);
        t4.setEditable(true);
        t5.setEditable(true);
        t6.setEditable(true);
        t7.setEditable(true);
        t8.setEditable(true);
        t9.setEditable(true);
        ep.setVisible(false);
        }  
        
        else if(ck==0)
        {
        t1.setText("");   
        t1.setEditable(true);
        t1.setBackground(new Color(255,255,204));

         t2.setText("");   
         t3.setText("");   
         t4.setText("");   
         t5.setText("");   
         t6.setText("");   
         t6.setEditable(true);
         t6.setBackground(new Color(255,255,204));
         t7.setText("");   
         t8.setText("");   
         t9.setText("");   
         t10.setText("");   
        t3.setEditable(false);
        t4.setEditable(false);
        t5.setEditable(false);
        t6.setEditable(false);
        t7.setEditable(false);
        t8.setEditable(false);
        t9.setEditable(false);
        ep.setVisible(true);

        if(bj==101) error.setText(" ! Please Input Valid Id ...");

        if(bj==102) error.setText(" ! Mobile Number dose not match ...");

        if(bj==103) error.setText(" ! Email ID dose not match ...");
 
        }
    
        rp.setVisible(false);
        rp.setVisible(true);
        }catch(Exception e){System.out.printf("Error = "+e);}
        }
    }//GEN-LAST:event_goActionPerformed

    private void t3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyPressed
        ep.setVisible(false);        // TODO add your handling code here:
        rp.setVisible(false);
        rp.setVisible(true);
        t3.requestFocus();
        t3.setBackground(new Color(255,255,204));
        // TODO add your handling code here:
    }//GEN-LAST:event_t3KeyPressed

    private void t4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyPressed
        ep.setVisible(false);        // TODO add your handling code here:
        rp.setVisible(false);
        rp.setVisible(true);
        t4.requestFocus();
        t4.setBackground(new Color(255,255,204));
        // TODO add your handling code here:
    }//GEN-LAST:event_t4KeyPressed

    private void t5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t5KeyPressed
        ep.setVisible(false);        // TODO add your handling code here:
        rp.setVisible(false);
        rp.setVisible(true);
        t5.requestFocus();
        t5.setBackground(new Color(255,255,204));
        // TODO add your handling code here:
    }//GEN-LAST:event_t5KeyPressed

    private void t6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t6KeyReleased
        if(t6.getText().length()>10){
        t6.setEditable(true);
        t6.setBackground(Color.red);
        mo=1;
        }
        if(t3.getText().length()==10)mo=0;
        
        k=15;
        // TODO add your handling code here:
    }//GEN-LAST:event_t6KeyReleased

    private void t7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t7KeyPressed
        ep.setVisible(false);        // TODO add your handling code here:
        rp.setVisible(false);
        rp.setVisible(true);
        t7.requestFocus();
        t7.setBackground(new Color(255,255,204));
    }//GEN-LAST:event_t7KeyPressed

    private void t8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t8KeyPressed
        ep.setVisible(false);        // TODO add your handling code here:
        rp.setVisible(false);
        rp.setVisible(true);
        t8.requestFocus();
        t8.setBackground(new Color(255,255,204));
        // TODO add your handling code here:
    }//GEN-LAST:event_t8KeyPressed

    private void t9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t9KeyPressed
        ep.setVisible(false);
        rp.setVisible(false);
        rp.setVisible(true);

int key=evt.getKeyCode();
if((key>=evt.VK_0 && key<=evt.VK_9)||(key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACK_SPACE || key==evt.VK_LEFT || key==evt.VK_RIGHT)
{
 t9.setEditable(true);
 t9.setBackground(new Color(255,255,204));
}
else
{
 t9.setEditable(false);
}
   t9.requestFocus();
    }//GEN-LAST:event_t9KeyPressed

    private void butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butActionPerformed
   String id=t2.getText();
   String s1=t3.getText();
   String s2=t4.getText();
   String s3=t7.getText();
   String s4=t8.getText();
   String s5=t5.getText();
   String s6=t6.getText();
   String s7=t9.getText();

   if(s7.isEmpty())
   {
    t9.setBackground(Color.red);   
    t9.requestFocus();
   }
   
   if(s4.isEmpty())
   {
    t8.setBackground(Color.red);   
    t8.requestFocus();
   }

   if(s3.isEmpty())
   {
    t7.setBackground(Color.red);   
    t7.requestFocus();
   }

   if(mo==1 || s6.isEmpty())
   {
    t6.setBackground(Color.red);   
    t6.requestFocus();
   }

   if(!s5.endsWith(".com") || s5.isEmpty())
   {
    t5.setBackground(Color.red);   
    t5.requestFocus();
       em=1;
   }
   else em=0;
   
   if(s2.isEmpty())
   {
    t4.setBackground(Color.red);   
    t4.requestFocus();
   }

   if(s1.isEmpty())
   {
    t3.setBackground(Color.red);   
    t3.requestFocus();
   }

if(!s1.isEmpty() && !s2.isEmpty() && !s3.isEmpty() && !s4.isEmpty() && !s7.isEmpty() && (em==0) && (mo==0))
{
    int num=0;
try
{

st.executeUpdate("update emp set pass='"+s1+"',nm='"+s2+"',mail='"+s5+"',mob='"+s6+"',adrs='"+s3+"',city='"+s4+"',salary='"+s7+"' where id='"+id+"';");

        cb2.setSelectedIndex(0);
        t1.setText("");         t1.setEditable(false);
        t2.setText("");         t3.setEditable(false);
        t3.setText("");         t4.setEditable(false);
        t4.setText("");         t5.setEditable(false);
        t5.setText("");         t6.setEditable(false);
        t6.setText("");         t7.setEditable(false);
        t7.setText("");         t8.setEditable(false);
        t8.setText("");         t9.setEditable(false);
        t9.setText("");         
        t10.setText(""); 

        ep.setVisible(true);
        error.setText(" Record Updated ...");
        rp.setVisible(false);
        rp.setVisible(true); 

}catch(Exception e){System.out.print("error = "+e);}
}
else
{
    ep.setVisible(true);
    error.setText(" ! Please Fill All Fields...");
    rp.setVisible(false);
    rp.setVisible(true); 
}        // TODO add your handling code here:
    }//GEN-LAST:event_butActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but;
    private javax.swing.JComboBox cb2;
    private javax.swing.JPanel ep;
    private javax.swing.JLabel error;
    private javax.swing.JButton go;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JPanel ri;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
