package hotel;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JPanel;
import java.sql.*;
import javax.swing.JOptionPane;

public class modrp extends javax.swing.JPanel {

JPanel rp;
int k=0;
Connection con=null;
Statement st=null;
ResultSet rs=null;
    
    public modrp(JPanel abc) {
        rp=abc;
        initComponents();
this.setBackground(new Color(0,0,0,0));
ep.setBackground(new Color(0,0,0,0));
inr.setBackground(new Color(0,0,0,0));
ri.setBackground(new Color(0,0,0,0));

ep.setVisible(false);
    
        try
        {
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost/HGP","root","thakur");
        st=con.createStatement();
        rs=st.executeQuery("select * from rtype;");
      while(rs.next())
        {
         cb.addItem(rs.getString(1).toString());   
        }
        }
        catch(Exception e)
        {  }
         t2.setEditable(false);   
         t3.setEditable(false);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ep = new javax.swing.JPanel();
        error = new javax.swing.JLabel();
        inr = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        but = new javax.swing.JButton();
        t3 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        ri = new javax.swing.JPanel();
        cb = new javax.swing.JComboBox();
        cb1 = new javax.swing.JComboBox();

        error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        error.setForeground(new java.awt.Color(204, 255, 204));
        error.setText("! Error");

        javax.swing.GroupLayout epLayout = new javax.swing.GroupLayout(ep);
        ep.setLayout(epLayout);
        epLayout.setHorizontalGroup(
            epLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );
        epLayout.setVerticalGroup(
            epLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        inr.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                inrMouseMoved(evt);
            }
        });

        l1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("  Type of Room");

        l3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText("  Room Number");

        l5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 255, 255));
        l5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l5.setText("  Charges / Day");

        but.setBackground(new java.awt.Color(0, 102, 102));
        but.setFont(new java.awt.Font("Bell Gothic Std Light", 3, 24)); // NOI18N
        but.setForeground(new java.awt.Color(255, 255, 255));
        but.setText("SAVE");
        but.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        but.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butActionPerformed(evt);
            }
        });

        t3.setBackground(new java.awt.Color(255, 255, 204));
        t3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t3.setForeground(new java.awt.Color(51, 51, 51));
        t3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t3KeyPressed(evt);
            }
        });

        t2.setBackground(new java.awt.Color(255, 255, 204));
        t2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t2.setForeground(new java.awt.Color(51, 51, 51));
        t2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t2KeyPressed(evt);
            }
        });

        t1.setEditable(false);
        t1.setBackground(new java.awt.Color(255, 255, 204));
        t1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t1.setForeground(new java.awt.Color(51, 51, 51));
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout inrLayout = new javax.swing.GroupLayout(inr);
        inr.setLayout(inrLayout);
        inrLayout.setHorizontalGroup(
            inrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inrLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(inrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inrLayout.createSequentialGroup()
                        .addGroup(inrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(inrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(t2)
                            .addComponent(t1))
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inrLayout.createSequentialGroup()
                        .addComponent(but, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        inrLayout.setVerticalGroup(
            inrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inrLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(inrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(inrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(inrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(but, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        ri.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                riMouseMoved(evt);
            }
        });

        cb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb.setForeground(new java.awt.Color(51, 51, 51));
        cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Type of Room" }));
        cb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbMouseClicked(evt);
            }
        });
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });

        cb1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb1.setForeground(new java.awt.Color(51, 51, 51));
        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Room Number" }));
        cb1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb1MouseClicked(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout riLayout = new javax.swing.GroupLayout(ri);
        ri.setLayout(riLayout);
        riLayout.setHorizontalGroup(
            riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb1, 0, 215, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        riLayout.setVerticalGroup(
            riLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(ep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(ri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(inr, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(ri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(inr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inrMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inrMouseMoved
    }//GEN-LAST:event_inrMouseMoved

    private void cbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMouseClicked
k=1;        // TODO add your handling code here:
    }//GEN-LAST:event_cbMouseClicked

    private void cb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb1MouseClicked
k=1;        // TODO add your handling code here:
    }//GEN-LAST:event_cb1MouseClicked

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
         if(cb1.getItemCount()>0)
         for(int i=cb1.getItemCount()-1;i>0;i--)
         cb1.removeItemAt(i);
  
         t1.setText("");
         t2.setText("");
         t3.setText("");
         t2.setEditable(false);   
         t3.setEditable(false);   
        
         if(cb.getSelectedIndex()!=0)
         {
        try
        {
        rs=st.executeQuery("select rno from rooms where rtp='"+cb.getSelectedItem().toString()+"';");
      while(rs.next())
        {
         cb1.addItem(rs.getString(1).toString());   
        }
        }catch(Exception e){  }
         t1.setText(cb.getSelectedItem().toString());
         }

         rp.setVisible(false);
         rp.setVisible(true);
    }//GEN-LAST:event_cbActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed

         t2.setText("");
         t3.setText("");
         t2.setEditable(false);   
         t3.setEditable(false);   
        
         if(cb1.getSelectedIndex()!=0)
         {
           t2.setText(cb1.getSelectedItem().toString());  
        try
        {
        rs=st.executeQuery("select cost from rooms where rtp='"+cb.getSelectedItem().toString()+"' AND rno='"+cb1.getSelectedItem().toString()+"';");
      while(rs.next())
        {
          t3.setText(rs.getString(1));  
        }
        }catch(Exception e){  }
        t2.setEditable(true);
        t3.setEditable(true);
        
         }

         rp.setVisible(false);
         rp.setVisible(true);
    }//GEN-LAST:event_cb1ActionPerformed

    private void butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butActionPerformed
     String s1=t1.getText();
     String s2=t2.getText();
     String s3=t3.getText();

        if(s3.isEmpty() || s2.isEmpty())
        {
        ep.setVisible(true);
        if(cb1.getSelectedIndex()!=0 && cb.getSelectedIndex()!=0)
        error.setText(" ! Please Fill All Fields ...");
        else
         error.setText(" ! Please Select Room Type And Number...");
        rp.setVisible(false);
        rp.setVisible(true); 
        }

        else
        {
  try{
              
        rs=st.executeQuery("select status from rooms where rno='"+cb1.getSelectedItem().toString()+"';");
        String stu="";
        while(rs.next()){stu=rs.getString(1); }
        
            if(stu.equals("Available"))
            {

     st.executeUpdate("update rooms set rno='"+s2+"',cost='"+s3+"' where rtp='"+s1+"' AND rno='"+cb1.getSelectedItem().toString()+"';");     
            }
            else
            {
             JOptionPane.showMessageDialog(null,"This Room is Booked.\n\nYou can not Modify..\n\n");   
            }
            }catch(Exception e){System.out.print(e);}

  
        if(cb1.getItemCount()>0)
        for(int i=cb1.getItemCount()-1;i>0;i--)
        cb1.removeItemAt(i);
        cb.setSelectedIndex(0);
        t1.setText(" ");
        t2.setText(" ");
        t3.setText(" ");
        t1.setEditable(false);   
        t2.setEditable(false);   
        t3.setEditable(false);   
        ep.setVisible(true);
        error.setText(" Recored Updated...");
        rp.setVisible(false);
        rp.setVisible(true); 
    }
    }//GEN-LAST:event_butActionPerformed

    private void t2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyPressed
    ep.setVisible(false);        // TODO add your handling code here:
        rp.setVisible(false);
        rp.setVisible(true);
        t2.requestFocus();
    }//GEN-LAST:event_t2KeyPressed

    private void t3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyPressed
    ep.setVisible(false);        // TODO add your handling code here:
        rp.setVisible(false);
        rp.setVisible(true);
        t3.requestFocus();
    }//GEN-LAST:event_t3KeyPressed

    private void riMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riMouseMoved
        if(k==1){
        rp.setVisible(false);
        rp.setVisible(true);
        }
        k=0;
    }//GEN-LAST:event_riMouseMoved

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but;
    private javax.swing.JComboBox cb;
    private javax.swing.JComboBox cb1;
    private javax.swing.JPanel ep;
    private javax.swing.JLabel error;
    private javax.swing.JPanel inr;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l5;
    private javax.swing.JPanel ri;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
