/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package hotel;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;
import java.sql.*;

/**
 *
 * @author This pc
 */
public class Pbill extends javax.swing.JPanel {

JPanel rp;
int k;
String id;
Connection con=null;
Statement st=null;
ResultSet rs=null;
    
    public Pbill(JPanel abc) {
        rp=abc;
        k=0;
        initComponents();
this.setBackground(new Color(0,0,0,0));
sr.setVisible(false);

     try
        {
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost/HGP","root","thakur");
        st=con.createStatement();
        rs=st.executeQuery("select id from hdb;");
      while(rs.next())
        {
         ids.addItem(rs.getString(1).toString());   
        }
        }
        catch(Exception e){}
          prt.setEnabled(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t = new javax.swing.JTextArea();
        ids = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        src = new javax.swing.JButton();
        sr = new javax.swing.JPanel();
        cb = new javax.swing.JComboBox();
        t1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        prt = new javax.swing.JButton();
        er = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        t.setEditable(false);
        t.setColumns(20);
        t.setFont(new java.awt.Font("Consolas", 2, 18)); // NOI18N
        t.setForeground(new java.awt.Color(51, 51, 51));
        t.setLineWrap(true);
        t.setRows(5);
        t.setAutoscrolls(false);
        t.setBorder(null);
        jScrollPane1.setViewportView(t);

        ids.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        ids.setForeground(new java.awt.Color(51, 51, 51));
        ids.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        ids.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ids.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OR");

        src.setBackground(new java.awt.Color(255, 255, 255));
        src.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        src.setForeground(new java.awt.Color(51, 51, 51));
        src.setText("Serach");
        src.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        src.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        src.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcActionPerformed(evt);
            }
        });

        sr.setBackground(new java.awt.Color(255, 255, 255));
        sr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        sr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cb.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        cb.setForeground(new java.awt.Color(51, 51, 51));
        cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Customer ID", "Mobile No", "Email ID" }));
        cb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        cb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });

        t1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t1KeyReleased(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Cancel");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Search");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout srLayout = new javax.swing.GroupLayout(sr);
        sr.setLayout(srLayout);
        srLayout.setHorizontalGroup(
            srLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(srLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(srLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(srLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(srLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        srLayout.setVerticalGroup(
            srLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(srLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(srLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        prt.setBackground(new java.awt.Color(255, 255, 255));
        prt.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        prt.setText("Print");
        prt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        prt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prtActionPerformed(evt);
            }
        });

        er.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        er.setForeground(new java.awt.Color(255, 51, 51));
        er.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ids, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(src, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(er, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(ids, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(src, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(sr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(er, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        t1.setText("");   
        t1.setEditable(true);
        t1.setBackground(Color.white);

        if(cb.getSelectedIndex()==0)
        {
         t1.setEditable(false);   
        }
        
        else if(cb.getSelectedIndex()==1)
        {
        t1.setEditable(false);
        t1.setText("HGP");
        t1.setEditable(true);
        t1.requestFocus();
       }
        t1.requestFocus();
    }//GEN-LAST:event_cbActionPerformed

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
        er.setText("");       
        rp.setVisible(false);
        rp.setVisible(true);

if(cb.getSelectedIndex()==2){
int key=evt.getKeyCode();
if((key>=evt.VK_0 && key<=evt.VK_9)||(key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACK_SPACE || key==evt.VK_LEFT || key==evt.VK_RIGHT)
{
 t1.setEditable(true);
 t1.setBackground(Color.white);
}
else{
 t1.setEditable(false);
}
   }
        t1.requestFocus();        
    }//GEN-LAST:event_t1KeyPressed

    private void t1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyReleased
        if(cb.getSelectedIndex()==2){
        if(t1.getText().length()>10){
        t1.setEditable(true);
        t1.setBackground(Color.red);
        }
        k=5;
        }
    }//GEN-LAST:event_t1KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        prt.setEnabled(false);
        t.setText("");
        src.setEnabled(true);
        cb.setSelectedIndex(0);
        t1.setText("");
        t1.setBackground(Color.white);
        er.setText("");       
        sr.setVisible(false);
        rp.setVisible(false);
        rp.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void srcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcActionPerformed
        prt.setEnabled(false);
        t.setText("");
        ids.setSelectedIndex(0);
        src.setEnabled(false);
        sr.setVisible(true);
        rp.setVisible(false);
        rp.setVisible(true);

    }//GEN-LAST:event_srcActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String out="";
        String gd=t1.getText();
        if(gd.isEmpty())
        {
        er.setText(" Please Input Customer ID ... ");
        rp.setVisible(false);
        rp.setVisible(true); 
        }

        else{
        String rec[]=new String[9];
        int bj=0,ck=0,tot=0,abcd=0;
        try{

           if(cb.getSelectedIndex()==1)
           {
           rs=st.executeQuery("select id,nm,rno,rmtp,cin,cout,cost,nod,fcost from hdb where id='"+gd+"';");
           bj=101;
           }

           if(cb.getSelectedIndex()==2)
           {
           rs=st.executeQuery("select id,nm,rno,rmtp,cin,cout,cost,nod,fcost from hdb where mob='"+gd+"';");
           bj=102;
           }

           if(cb.getSelectedIndex()==3)
           {
           rs=st.executeQuery("select id,nm,rno,rmtp,cin,cout,cost,nod,fcost from hdb where mail='"+gd+"';");
           bj=103;
           }

            while(rs.next())
        {  
            ck=1;
            
            rec[0]=rs.getString(1);
            rec[1]=rs.getString(2);
            rec[2]=rs.getString(3);
            rec[3]=rs.getString(4);
            rec[4]=rs.getString(5);
            rec[5]=rs.getString(6);
            rec[6]=rs.getString(7);
            rec[7]=rs.getString(8);
            rec[8]=rs.getString(9);
        }
       
        if(ck==1)
        {
     abcd=(Integer.parseInt(rec[7])*Integer.parseInt(rec[6]));
String str="";
      str+="\n\t\t    Invoice";
      str+="\n\t\t  ***********\n";
      str+="\n\n      Customer ID  \t:\t"+rec[0];
      str+="\n\n         Name      \t:\t"+rec[1];
      str+="\n\n     Room Number   \t:\t"+rec[2];
      str+="\n\n      Room Type    \t:\t"+rec[3];
      str+="\n\n    Check in Date  \t:\t"+rec[4];
      str+="\n\n    Check out Date \t:\t"+rec[5];
      str+="\n\n  Room Charge / Day\t:\t"+rec[6];
      str+="\n\n    Days of Stay   \t:\t"+rec[7];
      str+="\n\n    Food Charges   \t:\t"+rec[8];
      str+="\n\n    Room Charges   \t:\t"+abcd;
      str+="\n\n    Extra Charges  \t:\t10%";

      tot=(Integer.parseInt(rec[8])+abcd);
      tot+=tot*10/100;

      str+="\n--------------------------------------------\n";
      str+="\n\t\t   Total Amount =  "+tot+"\n";
      
        t.setText(str);
        prt.setEnabled(true);
        cb.setSelectedIndex(0);
        t1.setText("");
        t1.setBackground(Color.white);        
        }  
        
        else if(ck==0)
        {
        if(bj==101) er.setText(" ! Please Input Valid Id...");

        if(bj==102) er.setText(" ! Mobile Number dose not match...");

        if(bj==103) er.setText(" ! Email ID dose not match...");

        prt.setEnabled(false);
        t.setText("");
        }
        }catch(Exception e){}
        rp.setVisible(false);
        rp.setVisible(true); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void prtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prtActionPerformed
        try{
            t.print();
        }catch(Exception e){}
    }//GEN-LAST:event_prtActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
       if(k==5){
           if(t1.getText().length()>0 && t1.getText().length()<10)
           { 
               t1.setEditable(true);
               t1.setBackground(Color.red);
       }}
        k=0;
    }//GEN-LAST:event_formMouseMoved

    private void idsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idsActionPerformed
       if(ids.getSelectedIndex()==0){
          t.setText("");
          prt.setEnabled(false);
       }
       else{
           
        String gd=ids.getSelectedItem().toString();
        String rec[]=new String[9];
        int tot=0,abcd=0;
        try{
           rs=st.executeQuery("select id,nm,rno,rmtp,cin,cout,cost,nod,fcost from hdb where id='"+gd+"';");
           while(rs.next())
            {  
            
            rec[0]=rs.getString(1);
            rec[1]=rs.getString(2);
            rec[2]=rs.getString(3);
            rec[3]=rs.getString(4);
            rec[4]=rs.getString(5);
            rec[5]=rs.getString(6);
            rec[6]=rs.getString(7);
            rec[7]=rs.getString(8);
            rec[8]=rs.getString(9);
        }
       
     abcd=(Integer.parseInt(rec[7])*Integer.parseInt(rec[6]));
      String str="";
      str+="\n\t\t    Invoice";
      str+="\n\t\t  ***********\n";
      str+="\n\n      Customer ID  \t:\t"+rec[0];
      str+="\n\n         Name      \t:\t"+rec[1];
      str+="\n\n     Room Number   \t:\t"+rec[2];
      str+="\n\n      Room Type    \t:\t"+rec[3];
      str+="\n\n    Check in Date  \t:\t"+rec[4];
      str+="\n\n    Check out Date \t:\t"+rec[5];
      str+="\n\n  Room Charge / Day\t:\t"+rec[6];
      str+="\n\n    Days of Stay   \t:\t"+rec[7];
      str+="\n\n    Food Charges   \t:\t"+rec[8];
      str+="\n\n    Room Charges   \t:\t"+abcd;
      str+="\n\n    Extra Charges  \t:\t10%";

      tot=(Integer.parseInt(rec[8])+abcd);
      tot+=tot*10/100;

      str+="\n--------------------------------------------\n";
      str+="\n\t\t   Total Amount =  "+tot+"\n";
      
        t.setText(str);
        prt.setEnabled(true);
        cb.setSelectedIndex(0);
        t1.setText("");
        t1.setBackground(Color.white);        
        ids.setSelectedItem(rec[0]);
        }catch(Exception e){}
        er.setText("");    
        src.setEnabled(true);
        sr.setVisible(false);
        rp.setVisible(false);
        rp.setVisible(true);
       }
    }//GEN-LAST:event_idsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb;
    private javax.swing.JLabel er;
    private javax.swing.JComboBox ids;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton prt;
    private javax.swing.JPanel sr;
    private javax.swing.JButton src;
    private javax.swing.JTextArea t;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
