package hotel;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class searchp extends javax.swing.JPanel {

JPanel rp;
int k,lala=0,bj=0,ck=0;
String id;
Connection con=null;
Statement st=null;
ResultSet rs=null;
DefaultTableModel md=null;

public searchp(JPanel abc) {
        initComponents();
        rp=abc;
        k=0;
        id="";
this.setBackground(new Color(0,0,0,0));
tp.setBackground(new Color(0,0,0,0));
md=(DefaultTableModel)tb.getModel();
tb.getTableHeader().setFont(new Font("tahoma",Font.PLAIN,16));

        try
        {
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost/HGP","root","thakur");
        st=con.createStatement();
        }
        catch(Exception e)
        { System.out.print(e); }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb1 = new javax.swing.JComboBox();
        t1 = new javax.swing.JTextField();
        go = new javax.swing.JButton();
        tp = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ep = new javax.swing.JLabel();

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        cb1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb1.setForeground(new java.awt.Color(51, 51, 51));
        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Search", "Customer ID", "Mobile No", "Email ID" }));
        cb1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb1MouseClicked(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        t1.setEditable(false);
        t1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t1.setForeground(new java.awt.Color(51, 51, 51));
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t1KeyReleased(evt);
            }
        });

        go.setBackground(new java.awt.Color(0, 102, 102));
        go.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        go.setForeground(new java.awt.Color(255, 255, 255));
        go.setText("Go");
        go.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        go.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });

        tb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Room No.", "City", "Mobile No.", "Check in"
            }
        ));
        tb.setRowHeight(23);
        jScrollPane1.setViewportView(tb);

        javax.swing.GroupLayout tpLayout = new javax.swing.GroupLayout(tp);
        tp.setLayout(tpLayout);
        tpLayout.setHorizontalGroup(
            tpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        tpLayout.setVerticalGroup(
            tpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Delete Permanently");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        ep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ep.setForeground(new java.awt.Color(255, 51, 0));
        ep.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ep.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(go, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(ep, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(go))
                .addGap(29, 29, 29)
                .addComponent(ep, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        t1.setText("");   
        t1.setEditable(true);
        t1.setBackground(Color.white);
        if(lala==1) { md.removeRow(0); lala=0; }       

        if(cb1.getSelectedIndex()==0)
        {
         t1.setEditable(false);   
        }
        
        else if(cb1.getSelectedIndex()==1)
        {
        t1.setText("HGP");
        t1.requestFocus();
       }
        ep.setText("");
        rp.setVisible(false);
        rp.setVisible(true);
        t1.requestFocus();
        
    }//GEN-LAST:event_cb1ActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
          if(k==1){
        rp.setVisible(false);
        rp.setVisible(true);
          }

          if(k==5){
           if(t1.getText().length()>0 && t1.getText().length()<10)
           { 
               t1.setEditable(true);
               t1.setBackground(Color.red);
           }
          }
          k=0;
    }//GEN-LAST:event_formMouseMoved

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        String out="";
        String gd=t1.getText();
         ck=0;
         bj=0;
 
        if(lala==1) { md.removeRow(0); lala=0; }       

        try{

           if(cb1.getSelectedIndex()==1)
           {
           rs=st.executeQuery("select id,nm,rno,city,mob,cin,cout from booked where id='"+gd+"';");
           bj=101;
           }

           if(cb1.getSelectedIndex()==2)
           {
           rs=st.executeQuery("select id,nm,rno,city,mob,cin from booked where mob='"+gd+"';");
           bj=102;
           }

           if(cb1.getSelectedIndex()==3)
           {
           rs=st.executeQuery("select id,nm,rno,city,mob,cin from booked where mail='"+gd+"';");
           bj=103;
           }

       String rec[][]=new String[1][6];
        while(rs.next())
        {
            ck=1;
         rec[0][0]=rs.getString(1);
         rec[0][1]=rs.getString(2);
         rec[0][2]=rs.getString(3);
         rec[0][3]=rs.getString(4);
         rec[0][4]=rs.getString(5);
         rec[0][5]=rs.getString(6);
        }       

       if(ck==1)
        {       
        ep.setText("");
        rp.setVisible(false);
        rp.setVisible(true);
        md.addRow(rec[0]);
        lala=1;
        }  
        
        else if(ck==0)
        {

           if(cb1.getSelectedIndex()==1)
           {
           rs=st.executeQuery("select id,nm,rno,city,mob,cin,cout from hdb where id='"+gd+"';");
           bj=101;
           }

           if(cb1.getSelectedIndex()==2)
           {
           rs=st.executeQuery("select id,nm,rno,city,mob,cin from hdb where mob='"+gd+"';");
           bj=102;
           }

           if(cb1.getSelectedIndex()==3)
           {
           rs=st.executeQuery("select id,nm,rno,city,mob,cin from hdb where mail='"+gd+"';");
           bj=103;
           }

        while(rs.next())
        {
            ck=2;
         rec[0][0]=rs.getString(1);
         rec[0][1]=rs.getString(2);
         rec[0][2]=rs.getString(3);
         rec[0][3]=rs.getString(4);
         rec[0][4]=rs.getString(5);
         rec[0][5]=rs.getString(6);
        }       

       if(ck==2)
        {       
        ep.setText("");
        rp.setVisible(false);
        rp.setVisible(true);
        md.addRow(rec[0]);
        lala=1;
        }  
        
        else if(ck==0)
        {

        if(bj==101) ep.setText(" ! Please Input Valid Id...");

        if(bj==102) ep.setText(" ! Mobile Number dose not match...");

        if(bj==103) ep.setText(" ! Email ID dose not match...");

        if(lala==1) { md.removeRow(0); lala=0; }       
        rp.setVisible(false);
        rp.setVisible(true);

        }

        }
        }catch(Exception e){ System.out.print(e);}
    }//GEN-LAST:event_goActionPerformed

    private void cb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb1MouseClicked
        k=1;

    }//GEN-LAST:event_cb1MouseClicked

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
        ep.setText("");
        rp.setVisible(false);
        rp.setVisible(true);

if(cb1.getSelectedIndex()==2){
int key=evt.getKeyCode();
if((key>=evt.VK_0 && key<=evt.VK_9)||(key>=evt.VK_NUMPAD0 && key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACK_SPACE || key==evt.VK_LEFT || key==evt.VK_RIGHT)
{
 t1.setEditable(true);
 t1.setBackground(Color.WHITE);
}
else{
 t1.setEditable(false);
}
 }
   t1.requestFocus();
    }//GEN-LAST:event_t1KeyPressed

    private void t1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyReleased
        if(cb1.getSelectedIndex()==2){
        if(t1.getText().length()>10){
        t1.setEditable(true);
        t1.setBackground(Color.red);
        }
        k=5;
        }

    }//GEN-LAST:event_t1KeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        try{

        if(ck==2)
        {
            id=t1.getText();
            st.executeUpdate("delete from hdb where id='"+id+"';");
            t1.setText(" ");
            t1.setEditable(false);
           cb1.setSelectedIndex(0);
            ep.setText(" Recored is Successfully Removed ...");
        }
       else if(ck==1)
        {
            ep.setText(" ! You Can't Delete This Recored ...");
        }
        
       else{
            ep.setText(" ! Please input Customer ID ...");
       }

        rp.setVisible(false);
        rp.setVisible(true); 
        }catch(Exception e){System.out.printf("error = "+e);}
    }//GEN-LAST:event_jLabel1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JLabel ep;
    private javax.swing.JButton go;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    public javax.swing.JTable tb;
    private javax.swing.JPanel tp;
    // End of variables declaration//GEN-END:variables
}
